# Generated by Django 5.1.2 on 2024-11-22 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='rider',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='location',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='ride_requested',
        ),
        migrations.AddField(
            model_name='rider',
            name='contact_number',
            field=models.CharField(default='kll', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
