# Generated by Django 5.1.2 on 2024-11-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_otp_remove_rider_destination_remove_rider_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='last_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
